import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

import Link from "next/link";
import Button from "../src/components/reusables/Button";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-1 flex space-x-2">
        <Link href="/login">
          <a>
            <Button variant="outlined-primary">Login</Button>
          </a>
        </Link>
        <Link href="/register">
          <a>
            <Button variant="outlined-success">Register</Button>
          </a>
        </Link>
        <Link href="/dashboard">
          <a>
            <Button variant="outlined-success">Dashboard</Button>
          </a>
        </Link>
      </div>
    </div>
  );
};

export default Home;
