import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

import Link from "next/link";
import Button from "../src/components/reusables/Button";
import Modal from "../src/components/reusables/Modal";
import Confirmation from "../src/components/Dashboard/Modals/Confirmation";
import Success from "../src/components/Dashboard/Modals/Success";
import SingleSend from "../src/components/Dashboard/Modals/SingleSend";

const Home: NextPage = () => {
  const [open, setOpen] = React.useState<string>("");
  return (
    <div className={"overflow-hidden"}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-1 flex flex-wrap space-x-2 space-y-5">
        <Link href="/login" className="hidden">
          <a className="hidden">
            <Button variant="outlined-primary">Login</Button>
          </a>
        </Link>
        <Link href="/login">
          <a>
            <Button variant="outlined-primary">Login</Button>
          </a>
        </Link>
        <Link href="/register">
          <a>
            <Button variant="outlined-success">Register</Button>
          </a>
        </Link>
        <Link href="/dashboard">
          <a>
            <Button variant="outlined-success">Dashboard</Button>
          </a>
        </Link>
        <Button
          onClick={() => setOpen("confirmation")}
          variant="contained-primary"
        >
          Confirmation Model
        </Button>
        <Button onClick={() => setOpen("success")} variant="contained-success">
          Success Model
        </Button>
      </div>

      <Modal open={Boolean(open)} className="flex items-center justify-center">
        {open === "success" ? (
          <Success onScrim={() => setOpen("")} />
        ) : open === "confirmation" ? (
          <Confirmation onScrim={() => setOpen("")} />
        ) : null}
      </Modal>
    </div>
  );
};

export default Home;
