import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

import { FaBeer } from "react-icons/fa";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-1 flex space-x-2">
        <Link href="/login">
          <a>Login</a>
        </Link>
      </div>
    </div>
  );
};

export default Home;
